### ISSUE TITLE
Blog is missing!!!

### ISSUE THREAD

**Issue by sensorario** [DevRomagna/website#1]

**Comment by Fuminshou** [comment]
Sarebbe possibile agganciarlo al sito?
Sarebbe bello pubblicare li foto e slide degli eventi conclusi

**Comment by sensorario** [comment]
Che sito? C'e'  un sito?

**Comment by Fuminshou** [comment]
Mi pare di aver capito che @nicolaiarocci ha preso il dominio devromagna.org
Quindi è possibile metterlo in piedi.... il mio pensiero era proiettato al futuro

**Comment by nicolaiarocci** [comment]
Sì ragazzi appena posso metto qui una bozza del sito e poi apriamo alla collaborazione della community.

**Comment by nicolaiarocci** [comment]
Sito è online con pagina statica singola su devromagna.org. Manca ovviamente il logo :)
